before_install: 
  - npm cache clean
language: node_js
node_js:
- 8
script: npm run build
deploy:
  provider: pages
#  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: site
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: DMlEg3SHqVMid8eatErWPTDL1ygxdoXq36o9WmXa3r8JLyOz2S5APwEYcokOVanmnp0SvfowBviNIWOcxIsVCwtQchHooFl0hEFCMy0zu2bJUme2RGBKbnaCaTFq35r2xm17T/Jx7x3vAuGejNQnRwWpNEn0x2rmmIpBvbMCmNugx9ZXLjXdsDGJ9UjmPFWBQVmIolDbxUTXnvQdv/Botns2O/xUunrPFA4sx/njmvXRAvZc3nH1s2YRGlPJ9eTekd4PE90dMHI+E8adMbvuzjO4ukDirEiMgPivhXhY1Y3I2Oy6MyUge8pZTWYBNt3S2FGuZIvN/Jigab+PdS23kS4JfJBr8PPGXC7INulzyK7Z+DdC9nvhbXD/136Konav1V+mg7abNywPkxVvIwWGwvui9jdIDHXa6UfGupCQe6I0uzbGJsBCDHyf/MiyX8vNpFHwyIUeEdDiMOEu+R2c3k3vgA17uzhASGtDLOZ3nL0dCL2DEpmqXGC0+YuQW39xGMsK0SmWJEa4FrP9UucHmLGcKTAKG7FgKRNJygrnSaEUPeoJtYJ1wyu0zKLkKvZ2qEXFonEUK7WGpt6k276PwFtOAmkT5aU38qDc3vioCJzuWnnd4Mpqe0F0sXCzpWA5eFQkMGaMp5T3gfcWvz9xb5QHjvOPHXVuUIUht6PoVWU=
