PREFIX schema: <http://schema.org/>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>

SELECT ?idol ?belonging
WHERE {
  VALUES ?belonging {"CinderellaGirls"@en "765AS"@en "MillionStars"@en "315ProIdols"@en "283Pro"@en}
  ?s schema:name ?idol;
     imas:Title ?belonging.
} 