PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX imas: <https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>
SELECT ?unit (?name as ?member)
WHERE {
  ?s rdf:type imas:Unit;
     schema:name ?unit;
     schema:member ?m.
  ?m schema:name ?name;
}